version: '3.1'

#  docker-compose -f compose-etcd.yml up
#  docker-compose -f compose-etcd.yml down

services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.27
    expose:
      - 2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ~/Downloads/tmp/volumes/etcd/data:/etcd-data
    command: "/usr/local/bin/etcd \
      --name s1 \
      --data-dir /etcd-data \
      --listen-client-urls http://0.0.0.0:2379 \
      --advertise-client-urls http://0.0.0.0:2379 \
      --listen-peer-urls http://0.0.0.0:2380 \
      --initial-advertise-peer-urls http://0.0.0.0:2380 \
      --initial-cluster s1=http://0.0.0.0:2380 \
      --initial-cluster-token tkn \
      --initial-cluster-state new \
      --log-level info \
      --logger zap \
      --log-outputs stderr"

#
#volumes:
#

networks:
  default:
    external:
      name: etcd-network
