spring:
  application:
    name: identity-service
  datasource:
    platform: postgres
    url: jdbc:h2:mem:${spring.datasource.db.name:xxx};MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=true
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driverClassName: org.h2.Driver
  liquibase:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    url: ${spring.datasource.url}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
security:
  token:
    server: true
    client: false
