version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - java_redis_app_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  app_service:
    image: app:latest
    networks:
      - java_redis_app_network
    environment:
      REDIS_SERVICE_HOST: redis
      REDIS_SERVICE_HOST_PORT: 6379
    ports:
      - "9001:8080"

networks:
  java_redis_app_network:
