#apiVersion: v1
#kind: ResourceQuota
#metadata:
#  name: dev-quota
#spec:
#  hard:
#    services: "3"
#    cpu: "2000m"
#    memory: "2Gi"
#---
#apiVersion: "v1"
#kind: "LimitRange"
#metadata:
#  name: "dev-limits"
#spec:
#  limits:
#    - type: "Pod"
#      max:
#        cpu: "1000m"
#        memory: "500Mi"
#      min:
#        cpu: "500m"
#        memory: "200Mi"
#    - type: "Container"
#      max:
#        cpu: "1000m"
#        memory: "400Mi"
#      min:
#        cpu: "500m"
#        memory: "200Mi"
#      default:
#        cpu: "500m"
#        memory: "200Mi"
#      defaultRequest:
#        cpu: "500m"
#        memory: "200Mi"
#    - type: "PersistentVolumeClaim"
#      min:
#        storage: "100Mi"
#      max:
#        storage: "1Gi"
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: app-route
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  rules:
##    - host: counter.com
#    - http:
#        paths:
#          - backend:
#              service:
#                name: counter-app-service
#                port:
#                  number: 8080
#            path: /
#            pathType: Prefix
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: counter-app-service
#spec:
#  selector:
#    app: counter
#    context: dev
#  ports:
#    - port: 8080
#---
apiVersion: v1
kind: Service
metadata:
  name: counter-redis-service
spec:
  selector:
    app: redis
    context: dev
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
      context: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        context: dev
    spec:
      containers:
        - name: counter-redis-deployment
          image: redis:alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "500m"
              memory: 200Mi
            limits:
              cpu: "1000m"
              memory: 400Mi
          args:
            - "--save"
            - ""
            - "--appendonly"
            - "no"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app-deployment
spec:
  selector:
    matchLabels:
      app: counter
      context: dev
  replicas: 2
  template:
    metadata:
      labels:
        app: counter
        context: dev
    spec:
      containers:
        - name: counter-app
          image: abudzko/tmp:javaapp
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: 200Mi
            limits:
              cpu: "500m"
              memory: 400Mi
          env:
            - name: REDIS_SERVICE_HOST
              value: counter-redis-service
            - name: REDIS_SERVICE_HOST_PORT
              value: "6379"
