version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/home/aliaksei/Downloads/tmp/volumes/gitlab/config:/etc/gitlab'
      - '/home/aliaksei/Downloads/tmp/volumes/gitlab/logs:/var/log/gitlab'
      - '/home/aliaksei/Downloads/tmp/volumes/gitlab/data:/var/opt/gitlab'
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - '/home/aliaksei/Downloads/tmp/volumes/gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - CI_SERVER_URL=gitlab
      - REGISTRATION_TOKEN=GR1348941THoLz4nD3Chb--ZoPQy3
      - RUNNER_NAME=my-docker-runner
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=ubuntu:20.04
      - DOCKER_PRIVILEGED=true
