# docker-compose -f docker-compose-apps.yml up
# docker-compose -f docker-compose-apps.yml down
version: "3.9"
services:
  zoo-rest-app1:
    image: zoo-rest
    ports:
      # Ports are open not only for other services on the same network
      # but also to the host(localhost)
      - "8000:8080"
    hostname: zoo-rest1
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9091
      HTTP_SERVER_PORT: 8080
    networks:
      - zoo-kafka-external
      - zoo-haproxy-external
      - zoo-postgres-external
  zoo-rest-app2:
    image: zoo-rest
    ports:
      # Ports are open not only for other services on the same network
      # but also to the host(localhost)
      - "8001:8080"
    hostname: zoo-rest2
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9091
      HTTP_SERVER_PORT: 8080
    networks:
      - zoo-kafka-external
      - zoo-haproxy-external
      - zoo-postgres-external
  zoo-worker-app:
    image: zoo-worker
    hostname: zoo-worker
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9091
    networks:
      - zoo-kafka-external

networks:
  zoo-kafka-external:
    name: zoo-kafka
    external: true
  zoo-haproxy-external:
    name: zoo-haproxy
    external: true
  zoo-postgres-external:
    name: zoo-postgres
    external: true
  default:
    external:
      name: zoo
