# docker-compose -f docker-compose-postgres.yml up
# docker-compose -f docker-compose-postgres.yml down
version: "3.9"
#Setting up a streaming replication https://hub.docker.com/r/bitnami/postgresql
services:
  postgresql-master:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - "15432:5432"
    user: root #warning! workaround
    volumes:
      - ~/Downloads/tmp/volumes/pg/master:/bitnami/postgresql
      - ~/Downloads/tmp/volumes/pg/master/conf/:/bitnami/postgresql/conf/
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=zoo-db
  postgresql-slave1:
    image: 'bitnami/postgresql:15.3.0'
#    ports:
#      - "15434:5432"
    expose:
      - 5432
    depends_on:
      - postgresql-master
    user: root #warning! workaround
    volumes:
      - ~/Downloads/tmp/volumes/pg/slave1:/bitnami/postgresql
      - ~/Downloads/tmp/volumes/pg/slave1/conf/:/bitnami/postgresql/conf/
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
  postgresql-slave2:
    image: 'bitnami/postgresql:15.3.0'
#    ports:
#      - "15435:5432"
    expose:
      - 5432
    depends_on:
      - postgresql-master
    user: root #warning! workaround
    volumes:
      - ~/Downloads/tmp/volumes/pg/slave2:/bitnami/postgresql
      - ~/Downloads/tmp/volumes/pg/slave2/conf/:/bitnami/postgresql/conf/
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432

networks:
  default:
    external:
      name: zoo-postgres
